# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-54.1.1d39f3a"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-54.1.1d39f3a/all-cli_0.0.0-54.1.1d39f3a_darwin_amd64.tar.gz"
      sha256 "687318d3b816dbfe4a0c631c291199f0aabf5db1ad1589691e79b6273a4f0963"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-54.1.1d39f3a/all-cli_0.0.0-54.1.1d39f3a_darwin_arm64.tar.gz"
      sha256 "3c051638924bf14dc1e9cc77f048a8e59483c2f52e52b39808e7ff76c1bd82c2"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-54.1.1d39f3a/all-cli_0.0.0-54.1.1d39f3a_linux_amd64.tar.gz"
      sha256 "3c118c076fbf6a2a04a355ffd92dcbf61f2c7ffbbc409e42fc36da56cd2349c1"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-54.1.1d39f3a/all-cli_0.0.0-54.1.1d39f3a_linux_arm64.tar.gz"
      sha256 "1cc9fb7aaf12aa696029e6941df79ad06c20c9cfa2633042c6f9073f5ae857f0"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
