# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-77.1.ead7a26"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-77.1.ead7a26/all-cli_0.0.0-77.1.ead7a26_darwin_amd64.tar.gz"
      sha256 "7d22e3c6970db98be506970a43242e86523bbfced7887e8224da928e6d84d6f3"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-77.1.ead7a26/all-cli_0.0.0-77.1.ead7a26_darwin_arm64.tar.gz"
      sha256 "0afb48166ffeb1e84df5a92afe2bf474b3b3f407acae245fbdc2b47d8da10058"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-77.1.ead7a26/all-cli_0.0.0-77.1.ead7a26_linux_amd64.tar.gz"
      sha256 "fa75d3d3a3da7eb1c9228d556f920fb9e36e24a629ab3f32a5ba5259d3ce4f5b"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-77.1.ead7a26/all-cli_0.0.0-77.1.ead7a26_linux_arm64.tar.gz"
      sha256 "2b73eac276c6aabd663f1cc3b6148dc5f299987712d782ecc8095b285068d2e2"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
