# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AllCli < Formula
  desc "Inspect and manage common CLI tool contexts"
  homepage "https://github.com/oldwinter/all-cli"
  version "0.0.0-72.1.199c666"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-72.1.199c666/all-cli_0.0.0-72.1.199c666_darwin_amd64.tar.gz"
      sha256 "043fad19f843ef2fb2a8bc6ae6cf173be3fb02de67eaead12d6811baf3f32265"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-72.1.199c666/all-cli_0.0.0-72.1.199c666_darwin_arm64.tar.gz"
      sha256 "0a7290e77dfd24c48bbc188348b9def74b51e815c8169e6352503ec27d4e1e9a"

      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-72.1.199c666/all-cli_0.0.0-72.1.199c666_linux_amd64.tar.gz"
      sha256 "f76ea0eb472dd86d38e9e0ec8b3a69b73a7a60377816a1d59aae5676269e9965"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oldwinter/all-cli/releases/download/v0.0.0-72.1.199c666/all-cli_0.0.0-72.1.199c666_linux_arm64.tar.gz"
      sha256 "7bafe88fd17a9cb314807edeb533047938e907a45000a47a132be6be54b28318"
      define_method(:install) do
        bin.install "all-cli"
      end
    end
  end

  test do
    system "#{bin}/all-cli", "version"
  end
end
